# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DiffPASS',
                'doc_host': 'https://Bitbol-Lab.github.io',
                'git_url': 'https://github.com/Bitbol-Lab/DiffPASS',
                'lib_path': 'diffpass'},
  'syms': {'diffpass.core': {'diffpass.core.foo': ('core.html#foo', 'diffpass/core.py')}}}
